### ISSUE TITLE
求教，对搜索引擎是否友好呢？

### ISSUE THREAD

**Issue by crestin** [tmplink/tmpUI#16]
看了示例，页面加载完成后，查看页面源码是空的。如果这样，搜索引擎抓取不到吧？

谢谢！

**Comment by tmplink** [comment]
目前的情况是，除了 Google 外，其它各家搜索引擎都没办法支持很好单页应用的内容检索。
不过即便是支持单页应用的 Google 搜索，我也不建议让 Google 自己来爬。

最佳方案是，针对各家搜索引擎 bot 支持的规则，由一个单独的后端来制作 sitemap 提交到搜索引擎，搜索引擎可以很好的理解其中的内容，并映射到基于 tmpUI 构建的应用中。

tmpUI 本身的设计就是可以允许在服务端无重写配置的情况下也能完整处理路由。
